### ISSUE TITLE
🐞 Bug `mount: /usr/lib/libmount.so.1: version `MOUNT_2_39' not found (required by mount)`

### ISSUE THREAD

**Issue by VenomousSteam81** [chromebrew/chromebrew#10118]
**Describe the bug**
When using the `mount` command in a shell script, I get `mount: /usr/lib/libmount.so.1: version `MOUNT_2_39' not found (required by mount)`

**To Reproduce**

1. Add `sudo mount` to any script file
2. Execute said script file

My environment was (crosh, bash or VT-2):
VT-2

3. I executed the command(s) below:
      ```shell
      `./mounts.sh`
      ```

      Output:

      ```
      Password: 
      mount: /usr/lib/libmount.so.1: version `MOUNT_2_39' not found (required by mount)
      mount: /usr/lib/libmount.so.1: version `MOUNT_2_39' not found (required by mount)
      mount: /usr/lib/libmount.so.1: version `MOUNT_2_39' not found (required by mount)
      ```
**Expected behavior**
The script to mount my filesystems correctly without any errors

**Screenshots**
N/A

**System Information: Paste the output of `crew sysinfo -v` between the two `***` below.**
**If you cannot execute `crew`, display the output of `cat /etc/lsb-release` instead.**

***
<details><summary>Expand</summary>

- Architecture: `aarch64` (`armv7l`)
- Processor vendor: `ARM`
- User space: `32-bit`
- Chromebrew Kernel version: `5.15`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.49.5`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib`

- Last update in local repository: 91f0f2ac9 `lib/package: Get rid of `eval` strings  (#10117) (85 minutes ago)`

- OS variant: `Chrome OS`
- OS version: `hana-release/R124-15823.40.0`
- OS channel: `stable-channel`

</details>

***

**Additional context**
I am trying to create a script that will mount some folders from the rootfs for a chroot.

What I think needs to be done:

      - [ ] N/A
